services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"                  # host:container (avoid clashing with local 5432)
    volumes:
      - pgdata:/var/lib/postgresql/data
  back:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app                   
      - bundle:/usr/local/bundle 
    ports:
      - "3001:3000"              
    depends_on:
      - db
    command: >
      bash -lc "bin/rails db:prepare && bin/rails s -b 0.0.0.0 -p 3000"
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: "http://localhost:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - back

volumes:
  pgdata:
  bundle: