# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  port: 5432
  username: react_rails_boilerplate
  password: react_rails_boilerplate
  timeout: 5000

development:
  <<: *connection
  database: react_rails_boilerplate_dev

test:
  <<: *connection
  database: react_rails_boilerplate_test
